# 7장 예외처리

## Questions

1. 오류 코드보다 예외 처리?
2. try-catch-finally 먼저 작성
3. 미확인 예외
4. 예외에 의미 제공
5. 호출자를 고려한 예외 클래스 정의
6. 정상적인 흐름 정의
7. null 반환 금지
8. null 전달 금지

## Organize

오류 처리 코드로 프로그램 논리를 이해하기 어려워진다면 깨끗한 코드라 부르기 어렵다. 7장은 우아하고 고상하게 오류를 처리하는 기법과 고려사항을 소개한다.

### 오류 코드보다 예외

예외를 지원하지 않는 오래된 프로그래밍 언어는 오류 처리 시 플래그를 설정하거나 호출자에게 오류 코드를 반환하는 방법으로 처리했다.

```java
// bad
public class DeviceController { ...
	public void sendShutDown() { 
		DeviceHandle handle = getHandle(DEV1); 
		// Check the state of the device
		if (handle != DeviceHandle.INVALID) {
			// Save the device status to the record field 
			retrieveDeviceRecord(handle);
			// If not suspended, shut down
			if (record.getStatus() != DEVICE_SUSPENDED) {
				pauseDevice(handle); 
				clearDeviceWorkQueue(handle); 
				closeDevice(handle);
			} else {
				logger.log("Device suspended. Unable to shut down");
			}
		} else {
			logger.log("Invalid handle for: " + DEV1.toString()); }
		}
	... 
}

// good
public class DeviceController { ...
	public void sendShutDown() { 
		try {
			tryToShutDown();
		} catch (DeviceShutDownError e) {
			logger.log(e); 
		}
	}
	private void tryToShutDown() throws DeviceShutDownError { 
		DeviceHandle handle = getHandle(DEV1);
		DeviceRecord record = retrieveDeviceRecord(handle);
	
		pauseDevice(handle); 
		clearDeviceWorkQueue(handle); 
		closeDevice(handle);
	}
	private DeviceHandle getHandle(DeviceID id) { 
		...
		throw new DeviceShutDownError("Invalid handle for: " + id.toString());
		... 
	}
	... 
}
```

함수를 호출한 즉시 오류를 확인하는 방법은 잊어버리기 쉽다. 반면에 오류 발생 시 예외를 던지면 논리가 분리되어 코드가 깔끔해진다.

### try-catch-finally문부터 작성

try 블록에서 무슨 일이 생기든지 catch 블록은 프로그램 상태를 일관성 있게 유지해야 한다. 그러므로 예외가 발생할 코드를 짤 때는 try-catch-finally문으로 시작하는 편이 낫다.

```java
// test code
@Test(expected = StorageException.class)
public void retrieveSectionShouldThrowOnInvalidFileName() {
	sectionStore.retrieveSection("invalid - file"); 
}

// bad
public List<RecordedGrip> retrieveSection(String sectionName) { 
	// dummy return until we have a real implementation
	return new ArrayList<RecordedGrip>();
}

// good
public List<RecordedGrip> retrieveSection(String sectionName) { 
	try {
		FileInputStream stream = new FileInputStream(sectionName) 
	} catch (Exception e) {
		throw new StorageException("retrieval error", e); 
	}
	return new ArrayList<RecordedGrip>(); 
}

// better
public List<RecordedGrip> retrieveSection(String sectionName) {
	try {
		FileInputStream stream = new FileInputStream(sectionName);
		stream.close();
	} catch (FileNotFoundException e) {
		throw new StorageException("retrieval error”, e);
	}
	return new ArrayList<RecordedGrip>();
}
```

- bad: 예외를 던지는 코드가 없으므로 테스트 실패
- good: 예외를 던지긴 하지만 예외 유형을 좁힐 수 있다.
- better: 예외 유형을 좁혀 FileNotFoundException 에러를 던진다.
- Q. FileNotFoundException 같은 예외는 어디서 받아오는거??

    checked 예외 : ide에서 알려주는 경우가 많음

    일반적 : 라이브러리 docs에서 어떤 예외 던지는지 알려주는 경우가 많음

강제로 예외를 일으키는 테스트 케이스를 작성 후 테스트를 통과하는 코드를 작성하는 것을 권장한다. try 블록의 트랜잭션 범위를 자연스레 구현하게 되어 트랜잭션의 본질을 유지하기 쉬워진다.

- Q. 여기서 말하는 트랜잭션이란?

    DO or Nothing

### 미확인(unchecked) 예외를 사용하라

- 확인된 예외와 미확인 예외

    ![Untitled](images/7장%20예외처리/Untitled.png)

    1. 확인된 예외

        잘못된 코드가 아닌 잘못된 상황에서 발생하는 예외

        컴파일러에서 확인함.

        ex) IO / FileNotFound 등 RuntimeException 이외의 예외들

    2. 미확인 예외

        런타임시 잘못된 코드로 발생하는 예외

        컴파일러에서 확인하지 않기 때문에 미확인 예외

        ex) 산술 예외 / ArrayOutOfBound 등의 RuntimeException에 포함된 예외들

    참고 : [https://ko.strephonsays.com/checked-and-vs-unchecked-exception-in-java-3286](https://ko.strephonsays.com/checked-and-vs-unchecked-exception-in-java-3286)

자바 초창기에는 확인된 예외를 사용했다. 하지만 최근 확인된 예외가 반드시 필요하지는 않다는 분위기이다. C++, C#, 파이썬, 루비 등의 언어가 확인된 예외를 지원하지 않는다.

확인된 예외는 OCP(open closed principle)를 위반한다. 예외를 던졌는데 catch 블록이 세 단계 위에 있는 경우, 그 사이 메서드 모두에 예외를 정의해야 한다.

→ 이는 캡슐화를 깨뜨린다.

- 근데 위의 코드 예제도 확인된 예외 아닌가?

### 예외에 의미를 제공하라

예외를 던질 때 전후 상황을 충분히 덧붙여라. 자바가 모든 예외에 호출 스택을 제공하긴 하지만, 부족한 경우가 있다.

실패 연산 이름과 실패 유형 등의 정보를 담아 예외와 함께 던지자.

### 호출자를 고려해 예외 클래스를 정의하라

오류를 분류하는 방법 중 하나로 발생 위치로 분류할 수 있다. 혹은 유형으로도 분류가 가능하다. 하지만 오류를 정의 할 때 가장 중요한 관심사는 **오류를 잡아내는 방법**이다.

다음 사례는 외부 라이브러리를 호출하는 try-catch-finally 문을 포함한 코드로, 외부 라이브러리가 던질 예외를 모두 잡아낸다.

```java
// bad
ACMEPort port = new ACMEPort(12);
try {
	port.open();
} catch (DeviceResponseException e) {
	reportPortError(e);
	logger.log("Device response exception", e);
} catch (ATM1212UnlockedException e) {
	reportPortError(e);
	logger.log("Unlock exception", e);
} catch (GMXError e) {
	reportPortError(e);
	logger.log("Device response exception");
} finally {
	…
}

// good
LocalPort port = new LocalPort(12);
try {
	port.open();
} catch (PortDeviceFailure e) {
	reportError(e);
logger.log(e.getMessage(), e);
} finally {
	…
}

public class LocalPort {
	private ACMEPort innerPort;
	public LocalPort(int portNumber) {
		innerPort = new ACMEPort(portNumber);
	}
	public void open() {
		try {
			innerPort.open();
		} catch (DeviceResponseException e) {
			throw new PortDeviceFailure(e);
		} catch (ATM1212UnlockedException e) {
			throw new PortDeviceFailure(e);
		} catch (GMXError e) {
			throw new PortDeviceFailure(e);
		}
	}
	…
}
```

- bad

    오류 처리 방식

    1. 오류를 기록한다
    2. 프로그램을 계속 수행해도 좋은지 확인한다.

    이 경우는 예외 유형과 무관하게 거의 동일하게 예외를 처리한다.

- good

    LocalPort 클래스는 ACMEPort 클래스가 던지는 예뢰를 잡아 변환하는 wrapper 클래스이다. 외부 API를 사용할 때 wrapper 기법이 최선이다.

    wrapper 장점

    - 의존성이 줄어든다.
    - 다른 라이브러리로 전환이 쉽다.
    - 테스트하기 쉬워진다.
    - 특정 업체의 API 설계에 발목 잡히지 않는다.

예외 클래스에 포함된 정보로 오류를 구분해도 되는 경우는 예외 클래스가 하나만 있어도 충분하다. 한 예외는 잡아내고 다른 예외는 무시하도 괜찮은 경우라면 여러 예외 클래스를 사용한다.

### 정상 흐름을 정의하라

오류 감지가 프로그램 언저리로 밀려나는 순간이 생긴다. 외부 API를 감싸 독자적 예외를 던지고, 코드위에 처리기를 정의해 중단된 계산을 처리한다. 때로는 중단이 적합하지 않은 때도 있다.

```java
try {
	MealExpenses expenses = expenseReportDAO.getMeals(employee.getID());
	m_total += expenses.getTotal();
} catch(MealExpensesNotFound e) {
	m_total += getMealPerDiem();
}
```

식비를 비용으로 청구했다면 직원이 청구한 식비를 총계에 더한다. 식비를 청구하지 않으면 일일 기본 식비를 총계에 더한다.

```java
MealExpenses expenses = expenseReportDAO.getMeals(employee.getID());
m_total += expenses.getTotal();
public class PerDiemMealExpenses implements MealExpenses {
	public int getTotal() {
		// return the per diem default
	}
}
```

코드를 간소화 했다. ExpenseReportDAO를 고쳐 언제나 MealExpenses 객체를 반환한다. 청구한 식비가 없다면 일일 기본 식비를 반환하는 MealExpenses 객체를 반환한다.

이를 특수사례 패턴(Special case pattern)이라 한다. 클래스를 만들거나 객체를 조작해 특수 사례를 처리하는 방식이다.

### null을 반환하지 마라

흔히 오류를 생성하는 습관 중 하나다. 한줄 건너 하나씩 null을 확인하게 된다.

```java
public void registerItem(Item item) {
	if (item != null) {
		ItemRegistry registry = peristentStore.getItemRegistry();
		if (registry != null) {
			Item existing = registry.getItem(item.getID());
			if (existing.getBillingPeriod().hasRetailOwner()) {
				existing.register(item);
			}
		}
	}
}
```

위 코드에서 둘째 행에 null 확인이 빠졌다. peristentStore가 null이라면? NullPointerException이 발생할 것이다. 애플리케이션 아래서 날린 NullPointerException를 처리하기는 너무 곤란한다.

null 확인이 **너무 많다**. null을 반환하는 대신 예외를 던지거나 특수 사례 객체를 반환하자.

```java
// bad
List<Employee> employees = getEmployees();
	if (employees != null) {
		for(Employee e : employees) {
			totalPay += e.getPay();
	}
}

// good
List<Employee> employees = getEmployees();
for(Employee e : employees) {
	totalPay += e.getPay();
}
public List<Employee> getEmployees() {
	if( .. there are no employees .. ) 
		return Collections.emptyList();
}
```

아래와 같이 null 대신 빈 리스트를 반환하는 경우 코드가 깔끔해진다.

### null을 전달하지 마라

정상적인 인수로 null을 기대하는 API 가 아니라면 최대한 피하자

```java
// before
public class MetricsCalculator 
{
	public double xProjection(Point p1, Point p2) {
		return (p2.x – p1.x) * 1.5;
	}
	…
}

// 누군가 인수로 null을 전달한다면?
calculator.xProjection(null, new Point(12, 13))alculator.xProjection(null, new Point(12, 13))
// NullPointerException가 발생할 것이다

// after 1
public class MetricsCalculator 
{
	public double xProjection(Point p1, Point p2) {
		if (p1 == null || p2 == null) {
			throw InvalidArgumentException(
				"Invalid argument for MetricsCalculator.xProjection");
		}
		return (p2.x – p1.x) * 1.5;
	}
}

// after 2
public class MetricsCalculator 
{
	public double xProjection(Point p1, Point p2) {
		assert p1 != null : "p1 should not be null";
		assert p2 != null : "p2 should not be null";
		return (p2.x – p1.x) * 1.5;
	}
}
```

- before: 인수로 null을 전달하는 경우 NullPointerException가 발생한다
- after 1: 조금 나아졌지만 InvalidArgumentException 처리기가 필요하다.
- after 2: 코드는 읽기 편하지만 문제는 해결하지 못한다. null 입력시 오류가 발생한다.

대다수의 프로그래밍 언어는 null 인자를 적절히 처리하는 방법이 없다. 때문에 애초에 null을 넘기지 못하도록 금지하는 정책이 합리적이다.

### 결론

깨끗한 코드는 읽기도 좋아야 하지만 안정성도 높아야 한다. 오류 처리를 프로그램 논리와 분리해 독자적인 사안으로 고려하자. 독립적인 추론이 가능해지며 유지보수성도 높아진다.
